server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
 
spring:
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql

tmdb:
  api-key: ${TMDB_API_KEY}
